linters:
  disable-all: true
  enable:
    - asasalint         # Check for passing []any as any in variadic func(...any)
    - asciicheck        # Check for non-ASCII identifiers
    - bidichk           # Checks for dangerous unicode character sequences
    - bodyclose         # Checks whether HTTP response body is closed successfully
    - containedctx      # Detects struct contained context.Context field
    - contextcheck      # Check if a function uses a non-inherited context
    - decorder          # Check declaration order and count of types, constants, variables and functions
    - dogsled           # Checks assignments with too many blank identifiers
    - dupl              # Code clone detection
    - durationcheck     # Check for two durations multiplied together
    - errcheck          # Checking for unchecked errors
    - errchkjson        # Checks types passed to the json encoding functions. Reports unsupported types and optionally reports occasions where the check for the returned error can be omitted
    - errname           # Checks that sentinel errors are prefixed with `Err` and error types are suffixed with `Error`
    - errorlint         # Find code that will cause problems with error wrapping
    - execinquery       # query string checker
    - exhaustive        # Check exhaustiveness of enum switch statements
    - exportloopref     # Checks for pointers to enclosing loop variables
    - forbidigo         # Forbids identifiers
    - forcetypeassert   # Finds forced type assertions
    - funlen            # Detection of long functions
    - gochecknoinits    # Checks that no init functions are present in Go code
    - gocognit          # Computes and checks the cognitive complexity of functions
    - goconst           # Finds repeated strings that could be replaced by a constant
    - gocritic          # The most opinionated Go source code linter
    - godot             # Check if comments end in a period
    - godox             # Detection of FIXME, TODO and other comment keywords
    - goerr113          # Check error handling expressions
    - gofumpt           # Checks whether code was gofumpt-ed
    - gomoddirectives   # Manage the use of 'replace', 'retract', and 'excludes' in go.mod
    - goprintffuncname  # Checks that printf-like functions are named with `f` at the end
    - gosec             # Inspects source code for security problems
    - gosimple          # Specializes in simplifying code
    - govet             # Reports suspicious constructs, such as Printf calls whose arguments do not align with the format string
    - grouper           # An analyzer to analyze expression groups
    - importas          # Enforces consistent import aliases
    - ineffassign       # Detects when assignments to existing variables are not used
    - interfacebloat    # Checks the number of methods inside an interface
    - ireturn           # Accept interfaces, return concrete types
    - logrlint          # Check logr arguments
    - maintidx          # Measures the maintainability index of each function
    - makezero          # Finds slice declarations with non-zero initial length
    - misspell          # Finds commonly misspelled English words in comments
    - nakedret          # Finds naked returns in functions greater than a specified function length
    - nestif            # Reports deeply nested if statements
    - nilerr            # Finds the code that returns nil even if it checks that the error is not nil
    - nilnil            # Checks that there is no simultaneous return of `nil` error and an invalid value
    - nlreturn          # Checks for a new line before return and branch statements
    - noctx             # Finds sending HTTP request without context.Context
    - nolintlint        # Reports ill-formed or insufficient nolint directives
    - nosprintfhostport # Checks for misuse of Sprintf to construct a host with port in a URL
    - prealloc          # Finds slice declarations that could potentially be preallocated
    - predeclared       # Find code that shadows one of Go's predeclared identifiers
    - reassign          # Checks that package variables are not reassigned
    - revive            # Fast, configurable, extensible, flexible, and beautiful linter for Go
    - staticcheck       # Go vet on steroids, applying a ton of static analysis checks
    - tagliatelle       # Checks the struct tags
    - tenv              # Detects using os.Setenv instead of t.Setenv
    - testpackage       # Makes you use a separate _test package
    - thelper           # Detects test helpers without t.Helper() and checks the consistency of test helpers
    - tparallel         # Detects inappropriate usage of t.Parallel() method in Go test code
    - typecheck         # Like the front-end of a Go compiler, parses and type-checks Go code
    - unconvert         # Remove unnecessary type conversions
    - unparam           # Reports unused function parameters
    - unused            # Checks for unused constants, variables, functions and types
    - usestdlibvars     # Detect the possibility to use variables/constants from the Go standard library
    - wastedassign      # Finds wasted assignment statements
    - whitespace        # Detection of leading and trailing whitespace
    - wrapcheck         # Checks that errors returned from external packages are wrapped
    - wsl               # Whitespace Linter - Forces you to use empty lines!

    #- cyclop            # Checks function and package cyclomatic complexity
    #- depguard          # Checks if package imports are in a list of acceptable packages
    #- exhaustruct       # Checks if all structure fields are initialized
    #- gci               # Control package import order and make it always deterministic
    #- gochecknoglobals  # Checks that no globals are present
    #- gocyclo           # Computes and checks the cyclomatic complexity of functions
    #- gofmt             # Checks whether code was gofmt-ed
    #- goheader          # Checks if file header matches to pattern
    #- goimports         # Does everything that gofmt does and checks unused imports
    #- gomnd             # An analyzer to detect magic numbers
    #- gomodguard        # Allow and block list linter for direct Go module dependencies. This is different from depguard where there are different block types for example version constraints and module recommendations.
    #- lll               # Reports long lines
    #- nonamedreturns    # Reports all named returns
    #- paralleltest      # Detects missing usage of t.Parallel() method in tests
    #- promlinter        # Check Prometheus metrics naming via promlint
    #- rowserrcheck      # Checks whether err of rows is checked successfully
    #- sqlclosecheck     # Checks that sql.Rows and sql.Stmt are closed.
    #- stylecheck        # Replacement for golint
    #- varnamelen        # Checks that the length of a variable's name matches its scope

issues:
  exclude-use-default: false

linters-settings:
  gosec:
    excludes:
      - G104
      - G307
  nolintlint:
    allow-unused: false
    allow-leading-space: false
    require-explanation: true
    require-specific: true
