version: "2"
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - exhaustruct
    - gochecknoglobals
    - mnd
    - nonamedreturns
    - paralleltest
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    gosec:
      excludes:
        - G104
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - goconst
          - nestif
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - swaggo
